version: "3"
services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: always
    volumes:
      - ./backupDB:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: plugin_app
      MYSQL_ROOT_PASSWORD: root

  springboot-app:
    container_name: spring_app
    image: springboot-app
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
